applications/cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "app_cart"
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('add_to_cart/',views.AddToCartView.as_view(), name='add_to_cart'),
    path('delete_item/', views.DeleteProduct.as_view(), name='detele_item')

]

applications/product/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "app_product"
urlpatterns = [
    path('products/', views.PrductsView.as_view(), name='products'),

]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.cart.urls')),
    path('', include('applications.product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from model_utils.models import TimeStampedModel

from applications.product.models import Product
from .managers import CartManager

# Create your models here.

class Cart(TimeStampedModel):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, through="CartItem")
    objects = CartManager()

    def __str__(self) -> str:
        return f"Carrito: {self.pk} - Usuario: {self.user.username}"

    def total_price(self):
        total = 0

        for item in self.caritem_set.all():
            total += item.quantity * item.product.price
        
        return total

class CartItem(TimeStampedModel):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Cantidad', default=1)

    def __str__(self) -> str:
        return f"{self.product.name} x {self.quantity}"

applications/product/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from ckeditor.fields import RichTextField

# Create your models here.

class Product(TimeStampedModel):
    name = models.CharField('Producto', max_length=40)
    price = models.DecimalField('Precio',max_digits=10, decimal_places=2)
    description = RichTextField('Descripcion')
    image = models.ImageField('Imagen', upload_to="img-product")

    def __str__(self):
        return self.name
    

applications/cart/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, View
from django.http import HttpResponse
from django.shortcuts import redirect
from django.db.models import Sum, F

from .models import Cart, CartItem
from applications.product.models import Product
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.

class CartView(TemplateView):
    template_name = "cart/cart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        cart, created = Cart.objects.get_or_create(user=user)
        cart_items = cart.cartitem_set.select_related('product').annotate(total_quantity=Sum('quantity'),total_price=Sum(F('quantity') * F('product__price')))
        for item in cart_items:
            print(item)
        context["cart_items"]= cart_items
        return context
    
class AddToCartView(View):
    def get(self, request, *args, **kwargs):
        user =self.request.user
        product_id = request.GET.get('product_id')
        quantity = request.GET.get('quantity')
        cart, created = Cart.objects.get_or_create(user=user)
        product = Product.objects.get(id=product_id)
        cart_item = CartItem.objects.create(cart=cart, product=product, quantity=quantity)
        messages.success(self.request, "Se Agrego producto al carrito")
        return redirect(reverse_lazy('app_product:products'))


class DeleteProduct(View):
    def post(self, request, *args, **kwargs):
        user =self.request.user
        product_id = self.request.POST.get('product_id')
        cart = Cart.objects.get(user=user)
        try:
            cart_item = CartItem.objects.get(cart=cart, product_id=product_id)
        except CartItem.DoesNotExist:
            return redirect(reverse_lazy('app_cart:cart'))

        cart_item.delete()
        messages.error(self.request, "Eliminación de producto exitosa")
        
        return redirect(reverse_lazy('app_cart:cart'))
     

applications/product/views.py
from django.shortcuts import render
from django.views.generic import ListView

from .models import Product
# Create your views here.

class PrductsView(ListView):
    template_name = "products/products.html"
    model = Product
    context_object_name = "products"

templates/cart/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart</title>
</head>
<body>

    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    {% for item in cart_items %}
    <p><strong>Producto: {{ item.product.name }}</strong></p>
    <img src="{{item.product.image.url}}" alt="{{produc.image.url}}" style="height: 150px;">
    <p><strong>Descripcion:</strong> {{item.product.description|safe}}</p>
    <p><strong>Precio por unidad:</strong> {{ item.product.price }}</p>
    <p><strong>Cantidad:</strong> {{ item.total_quantity }}</p>
    <p><strong>Precio total:</strong> {{ item.total_price }}</p>
    <form action="{% url 'app_cart:detele_item' %}" method="POST">{% csrf_token %}
        <input type="number" name="product_id" value="{{item.product.id}}" style="display: none;">
        <button type="submit">Eliminar Producto</button>
    </form>
    <hr>
{% endfor %}
</body>
</html>

templates/products/products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productos</title>
</head>
<body>

    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}

    {% for product in products %}
        <p>Nombre: {{product.name}}</p>
        <img src="{{product.image.url}}" alt="{{produc.image.url}}" style="height: 150px;">
        <p>Descripcion: {{product.description|safe}}</p>
        <p>Precio: {{product.price}}</p>
        <form action="{% url 'app_cart:add_to_cart' %}" method="get">{% csrf_token %}
            <input type="number" name="product_id" value="{{product.id}}" style="display: none;">
            <input type="number" name="quantity" placeholder="Cantidad" required>
            <button type="submit">Agregar al carrito</button>
        </form>
    {% endfor %}
</body>
</html>